/*
 * Copyright (c) 2019-2021, NVIDIA CORPORATION.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-FileCopyrightText: Copyright (c) 2019-2021 NVIDIA CORPORATION
 * SPDX-License-Identifier: Apache-2.0
 */

#version 460
// https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_tracing.txt
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require


#include "raycommon.glsl"
#include "random.glsl"
// #include "host_device.h"
#include "../../TrVulkanShader.h"

// clang-format off
layout(location = 0) rayPayloadEXT hitPayload prd;
// uniform变量：topLevelAS
// 变量类型：accelerationStructureEXT
layout(set = 0, binding = Tlas) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = OutImage, rgba32f) uniform image2D image;
// uniform块名：_GlobalUniforms (uniform块可以包含多个不同类型的uniform变量)
// TrGlobalUniforms：用户定义的类型
// uni：类型实例
layout(set = 1, binding = Globals) uniform _GlobalUniforms { TrGlobalUniforms uni; };
layout(push_constant) uniform _PushConstantRay { TrPushConstantRay pushConstantRay; };
// clang-format on


void main()
{
  prd.seed = tea(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, pushConstantRay.mFrame);
  vec3 hitValues = vec3(0);
  
  for(int smpl = 0; smpl < pushConstantRay.mNumRayGenSamples; smpl++)
  {
      float r1 = rnd(prd.seed);
      float r2 = rnd(prd.seed);
      vec2 subpixelJitter = pushConstantRay.mFrame == 0 ? vec2(0.5f, 0.5f) : vec2(r1, r2);
      
      const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + subpixelJitter;
      const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
      // [0, 1] -> [-1, 1]
      vec2       d           = inUV * 2.0 - 1.0;
    
      // obtain the origin and direction of the ray
      vec4 origin    = uni.mViewInverse * vec4(0, 0, 0, 1);
      vec4 target    = uni.mProjInverse * vec4(d.x, d.y, 1, 1);
      vec4 direction = uni.mViewInverse * vec4(normalize(target.xyz), 0);
    
      // uint  rayFlags = gl_RayFlagsOpaqueEXT; // will skip the any hit shader
      uint  rayFlags = gl_RayFlagsNoneEXT; 
      float tMin     = 0.001;
      float tMax     = 10000.0;
    
      //traceRayEXT(topLevelAS,     // acceleration structure
      //            rayFlags,       // rayFlags
      //            0xFF,           // cullMask
      //            0,              // sbtRecordOffset
      //            0,              // sbtRecordStride
      //            0,              // missIndex
      //            origin.xyz,     // ray origin
      //            tMin,           // ray min range
      //            direction.xyz,  // ray direction
      //            tMax,           // ray max range
      //            0               // payload (location = 0)
      //);
      
      traceRayEXT(topLevelAS, rayFlags, 0xFF, 0, 0, 0, origin.xyz, tMin, direction.xyz, tMax, 0);
      hitValues += prd.hitValue;
  }
  prd.hitValue = hitValues / pushConstantRay.mNumRayGenSamples;

  if(pushConstantRay.mFrame > 0)
  {
    float alpha = 1.0f / float(pushConstantRay.mFrame);  
    vec3 oldColor = imageLoad(image, ivec2(gl_LaunchIDEXT.xy)).xyz;
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(mix(oldColor, prd.hitValue, alpha), 1.0));
  }
  else
  {
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(prd.hitValue, 1.0));
  }
}
